---
name: frugallocker
services:
  jenkins:
    build:
        dockerfile: jenkins.Dockerfile
    volumes:
      - jenkins_data:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
  nginx:
    image: nginx
    volumes:
      - jenkins_data:/var/www/jenkins:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8081:80 
volumes:
  jenkins_data:
