---
name: frugallocker
services:
  jenkins:
    build:
        dockerfile: jenkins.Dockerfile
    volumes:
      - jenkins_data:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
volumes:
  jenkins_data:
